sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: fsHpAUn+hVN4T066wC0DGM5IqD7JSIMX5Y/wCsEsVnKJny/LH5itJU9G2+qzvkHt3VOze0NrKGu1Xmr3bS45aLWUKcx7LT4KUGTwNVO0OMZdKS6R4zEXhS+8xsK6P8f9mdkXbyyVJ/C7nM7rM/Igor0UA8sfKqi9mEY5prZmAoZAoSouKXDvuHrB8BHOit2851MjvdSAbbfkB4F5nzP6p1edVDkmudzWNFCAKCSDm/TB2Mp6LS/2I0oJO0wlIN0R2MNiL85+FnqSog0ucHxACkSc2H9uwngCp3T/rr2lAxas2tt+MbuA06n2V2PJ8j7pg7hkVQAERtYkRDWn0gPu8ipulqZVbNxtGVCXqXCBRpLDQMllkWOS9qrSHj+30nOShcz6+DE4qr2AmBwUvP+13E5Si4orNV+/BbCdwJT5KFrjVP5zBygqgv2u6VGgUuDKoeiFlTep89N6aaqNEOj09nitwKeTzO373peIZaFZNgSWM4yhU+lyZTMovG+zcsWu8FrLmcRi6nAAcBvg9vy9ZMOHC7MNeGFO+oP19pxTH/zpVSdMWQU80pHQtpMq6itVGpPeFFOQVYQz8oeXTl+hgqIATjc3kKzHrtQcmJsMWwhXrcq8zdeYltXBZNcCR+wdHozZQ/g5+u8/p8ig2WccWYhyu5Kjar9tKltO6zw3u+Y=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Diary-of-Samuel-Pepys---Volume-73--April-May-1669_4198
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy